using System;
using System.Collections.Generic;

namespace JsonBenchmarks
{
    public partial class TestData
    {
        public static readonly SimpleStructure SimpleJsonObject = new SimpleStructure
        {
            value1 = "this is value 1",
            value2 = "and this is value 2"
        };

        public static readonly ComplexStructure ComplexJsonObject = new ComplexStructure
        {
            IntValue = 100,
            LongValue = 999_999_999_999,
            DateTimeOffsetValue = new DateTimeOffset (2020, 01, 01, 0, 0, 0, TimeSpan.FromHours (1)),
            DateTimeValue = new DateTime (2020, 1, 1),
            GuidValue = Guid.NewGuid (),
            IsTrue = true,
            Description = "Nobody ain't got no time for that",
            Records = new List<SimpleStructure>
            {
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            new SimpleStructure { value1 = "val 1", value2 = "val 2" },
            }
        };
    }
}